import Poincare.Topology.SphericalSpaceForm
import Poincare.Topology.SphereBundlesOverS1
import Poincare.Topology.ConnectedSum
import Poincare.Topology.AllowedSummands
import Poincare.Topology.PrimeDecompositionInterface
import Poincare.Topology.SurgeryTopology
import Poincare.Topology.ExtinctionToClassification
import Poincare.Topology.SimplyConnectedEndgame
